### ISSUE TITLE
Issue on production servers.

### ISSUE THREAD

**Issue by yangit** [apollographql/optics-agent-js#129] opened 2017-09-22 09:42 UTC
Today we had an issue on our prod servers.
I'm still looking into it but apparently optics middleware took down our graphql server with the following error logged to console.
```
OPTICS Backend error 502 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```

Could this be?
Is not optics reporter isolated from optics middleware?

**Comment by rohit2b** [comment] 2017-09-22 12:20
Hi @yangit - thanks for letting us know. What agent version are you using?

Can you please send these details into our Optics support at support@apollodata.com?

**Comment by vincentdesmares** [comment] 2017-09-26 23:48
We also have this error showing in our logs.

With also 

> OPTICS Backend error 406 Invalid PSK format

Does someone have an idea to solve the problem?

Some details about the issue:

Optic agent version : "1.1.6"
Server: Ubuntu 16.4.02 LTS (xenial)

Regards.

**Comment by timbotnik** [comment] 2017-09-26 23:54
@vincentdesmares there is a bug recently fixed in v1.1.7 that caused errors to be logged to the console prematurely (before performing retries).  We expect _some_ 502s and retries to the Optics ingress, so the issue is just that we were logging the error at the wrong time (causing concern for people who experience it).  Most likely it is nothing to worry about, and the logging issue should be fixed if you update to 1.1.7.

**Comment by timbotnik** [comment] 2017-09-26 23:55
502 issue here: https://github.com/apollographql/optics-agent-js/issues/97

**Comment by timbotnik** [comment] 2017-09-27 00:10
@vincentdesmares a 406 error is likely due to a mistake in your API key.  Can you make sure that you have accurately copied the key to your server?

**Comment by vincentdesmares** [comment] 2017-09-27 00:20
It was indeed our key.

So a 406 means “invalid API key”.

Thanks for the quick support!

**Comment by timbotnik** [comment] 2017-09-27 01:28
@yangit can you provide the version of `optics-agent` you are using?  I am hoping that your issue is the same as #97 fixed by v1.1.7.

**Comment by yangit** [comment] 2017-09-27 01:31
It was indeed `1.1.6`
The issue we had with prod servers was that our logging system used to log `req` object by default.
And optics adds a lot of meta info under `req._opticsContext` key. So our logger ended up logging gigabytes of data and that completely stalled our prod server.

I logs I also saw the above message from optics which turned out to be unrelated to real issue.

Nobody to blame here.
Everything is fixed.

**Comment by timbotnik** [comment] 2017-09-27 01:33
@yangit Glad to hear that you found the root cause, and sorry for the red-herring in the logs!  Closing this issue now.

**Closed by timbotnik** 2017-09-27 01:33 UTC
